version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: exemple
      DB_NAME: support_tickets

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: exemple
      MYSQL_DATABASE: support_tickets
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend-lite:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data:
