services:
  backend:
    build: 
      context: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: "${DB_HOST}"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_NAME: "${DB_NAME}"
    env_file:
      - .env
    command: sh -c "sleep 10 && node server.js"

  frontend:
    container_name: frontend_tickets
    image: nginx:alpine
    ports:
      - "10000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "3306:3306"

volumes:
  db_data: